### ISSUE TITLE
remove theme

### ISSUE THREAD

**Issue by labkey-kevink** [LabKey/labkey-api-js#9]
The current checked in theme is just the default.  We have no plans to theme the docs, so we can remove it.

**Comment by labkey-nicka** [comment]
It's not the default. This was added to be able to override certain characteristics of the theme templates. For example, the default has quotes around each `Global` and most links.

![image](https://user-images.githubusercontent.com/3926239/75371504-b8a0f780-587b-11ea-81a4-96c2a77ce3d7.png)

where as that is not the case in the [current version](https://labkey.github.io/labkey-api-js/globals.html).

**Comment by labkey-nicka** [comment]
Removed with PR #36.
